### ISSUE TITLE
compile linux 

### ISSUE THREAD

**Issue by arpu** [neveraway/oclJPEGDecoder#2]
with nvidia cuda opencl

g++ main.cpp bitstream.cpp cpuIDCT8x8.cpp decoder.cpp  huffman.cpp  oclDCT8x8.cpp parser.cpp stdafx.cpp -std=c++11 -I/usr/local/cuda-7.5/include -L/usr/local/cuda-7.5/lib64 -lOpenCL -o oclJPEGDecoder

and this small changes https://gist.github.com/arpu/33a26cc3bbb235bef3d2f30c06d10f52

**Comment by neveraway** [comment]
patch applied. thx for your support!
